### ISSUE TITLE
Error When opening in Learn IDE 3

### ISSUE THREAD

**Issue by cam-benfield** [learn-co-curriculum/dsc-data-science-env-installation-v2-1#2]
Getting an error that looks like this when opening through Learn IDE:

` // ♥ learn open dsc-data-science-env-installation-v2-1-onl01-dtsc-pt-012120
Looking for lesson...
Traceback (most recent call last):
        11: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        10: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
         9: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-open:23:in `<main>'
         8: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-open:23:in `load'       
         7: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/bin/learn-open:7:in `<top (required)>'
         6: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/opener.rb:12:in `run'
         5: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/opener.rb:38:in `run'
         4: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.rb:19:in `classify'
         3: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.rb:19:in `find'
         2: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.rb:19:in `each'
         1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.rb:20:in `block in classify'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons/ios_lesson.rb:6:in `detect': undefined meth
od `&' for "python":String (NoMethodError)`

**Comment by cam-benfield** [comment]
Seems it may not be an issue with this particular repo, but with the IDE itself.
